Repository exasol/exasol-testcontainers, pull requests merged in 2020-07, with the labels that each got.

#64 #63: Added ossindex-maven-plugin and versions-maven-plugin, updated d…
  README.md
  doc/changes/changelog.md
  doc/changes/changes-2.0.3.md
  pom.xml
Labels: refactoring

#67 #66: Fixed requirements tracing.
  doc/changes/changes-2.0.3.md
  src/main/java/com/exasol/exaoperation/ExaOperationEmulator.java
Labels: refactoring

#65 #54: Fix wait when replacing file in bucket
  .travis.yml
  doc/changes/changes-2.1.0.md
  doc/design.md
  doc/system_requirements.md
  doc/user_guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/bucketfs/Bucket.java
  src/main/java/com/exasol/clusterlogs/LogPatternDetector.java
  src/main/java/com/exasol/clusterlogs/LogPatternDetectorFactory.java
  src/main/java/com/exasol/config/ClusterConfiguration.java
  src/main/java/com/exasol/containers/ExasolContainer.java
  src/main/java/com/exasol/containers/ExasolContainerConstants.java
  src/main/java/com/exasol/containers/ExasolDockerImageReference.java
  src/main/java/com/exasol/containers/wait/strategy/BucketFsWaitStrategy.java
  src/main/java/com/exasol/containers/wait/strategy/LogFileEntryWaitStrategy.java
  src/main/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategy.java
  src/test/java/com/exasol/bucketfs/BucketContentSyncIT.java
  src/test/java/com/exasol/bucketfs/BucketIT.java
  src/test/java/com/exasol/containers/ExasolContainerTest.java
  src/test/java/com/exasol/containers/ExasolDockerImageReferenceTest.java
  src/test/java/com/exasol/containers/MessageWriter.java
  src/test/java/com/exasol/containers/OptionalServicesIT.java
  src/test/java/com/exasol/containers/wait/strategy/AbstractServiceWaitStrategyTest.java
  src/test/java/com/exasol/containers/wait/strategy/BucketFsWaitStrategyTest.java
  src/test/java/com/exasol/containers/wait/strategy/UdfContainerWaitStrategyTest.java
  src/test/java/com/exasol/exaconf/ConfigurationParserTest.java
  src/test/resources/logging.properties
Labels: bug

#69 Feature/68 list of exasol version
  doc/changes/changes-2.1.0.md
  doc/design.md
  doc/user_guide/user_guide.md
  src/main/java/com/exasol/containers/ExasolContainer.java
  src/main/java/com/exasol/containers/ExasolDockerImageReference.java
  src/test/java/com/exasol/containers/ExasolDockerImageReferenceTest.java
Labels: feature
