Repository exasol/exasol-testcontainers, pull requests merged in 2020-03, with the labels that each got.

#45 #44: Allow dash in plug-in package name.
  pom.xml
  src/main/java/com/exasol/exaoperation/plugin/Plugin.java
  src/test/java/com/exasol/exaoperation/plugin/PluginTest.java
Labels: bug

#47 Feature/46 support drs plugin
  doc/design.md
  doc/system_requirements.md
  doc/user_guide/user_guide.md
  pom.xml
  src/main/java/com/exasol/exaoperation/ExaOperation.java
  src/main/java/com/exasol/exaoperation/ExaOperationEmulator.java
  src/main/java/com/exasol/exaoperation/plugin/Plugin.java
  src/test/java/com/exasol/exaoperation/plugin/PluginIT.java
  src/test/sh/Plugin.Testing.Stub-1.0.0-2020-02-02.pkg
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/install
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/on_boot
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/plugin-functions
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/restart
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/start
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/status
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/stop
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/uninstall
Labels: documentation, feature, refactoring

#50 #48: Fix temp directory for Windows Host
  src/main/java/com/exasol/exaoperation/ExaOperationEmulator.java
  src/test/java/com/exasol/exaoperation/ExaOperationEmulatorIT.java
  src/test/java/com/exasol/exaoperation/ExaOperationEmulatorTest.java
  src/test/java/com/exasol/exaoperation/plugin/PluginStub.java
  src/test/java/org/testcontainers/containers/ExecResultFactory.java
  src/test/sh/Plugin.Testing.Broken-1.0.0-2020-03-20.pkg
Labels: bug

#51 Refactoring/49 port plugin functions to bash
  pom.xml
  src/main/java/com/exasol/exaconf/ConfigurationParser.java
  src/main/java/com/exasol/exaoperation/plugin/Plugin.java
  src/test/java/com/exasol/exaconf/ConfigurationParserTest.java
  src/test/sh/Plugin.Testing.Stub-1.0.0-2020-02-02.pkg
  src/test/sh/Plugin.Testing.Stub-1.0.0/usr/opt/EXAplugins/Testing.Stub-1.0.0/exaoperation-gate/plugin-functions
Labels: refactoring
